name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      hello-x--tag_name: ${{ steps.release.outputs.hello-x--tag_name}}
      hello-x--release_created: ${{ steps.release.outputs.hello-x--release_created}}
      hello-y--tag_name: ${{ steps.release.outputs.hello-y--tag_name}}
      hello-y--release_created: ${{ steps.release.outputs.hello-y--release_created}}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo '${{ toJson(steps.release.outputs) }}'


  release-hello-x:
    if: ${{needs.release-please.outputs.hello-x--release_created}}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - uses: actions/checkout@v4
      - name: Create source code archive
        run: |
          cd hello-x
          zip -r ../hello-x-build.zip ./* --exclude "*.git*" "*.pyc" "__pycache__/*" "*.egg-info/*"
          cd ..
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.hello-x--tag_name }} hello-x-build.zip

  release-hello-y:
    if: ${{needs.release-please.outputs.hello-y--release_created}}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - uses: actions/checkout@v4
      - name: Create source code archive
        run: |
          cd hello-y
          zip -r ../hello-y-build.zip ./* --exclude "*.git*" "*.pyc" "__pycache__/*" "*.egg-info/*"
          cd ..
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.hello-y--tag_name }} hello-y-build.zip